### ISSUE TITLE
Когда прода?

### ISSUE THREAD

**Issue by NikoLuke** [cvetkof/web#1]

**Comment by cvetkof** [comment]
что за "прода"?

**Comment by NikoLuke** [comment]
продакшн)

**Comment by cvetkof** [comment]
ахахахах а как ты вообще сюда зашел?

**Comment by cvetkof** [comment]
тебе пришло какое-то оповещение что я начал пушить сюда?

**Comment by cvetkof** [comment]
делай свою ветку и допиливай мой проджект ахахха

**Comment by NikoLuke** [comment]
нет, тема ткнул носом в мой гит, опустил меня

**Comment by cvetkof** [comment]
тема знает JS? если знает, надо с ним побазарить, потому что я щас в ступоре, работа встала

**Comment by NikoLuke** [comment]
неа, не знает
он андроид

**Comment by NikoLuke** [comment]
я asp.net начал
только хз, стоит ли
нужен проект какой-то, ибо не интересно так

**Comment by cvetkof** [comment]
печаль, не к кому обратиться совсем, буду в одного значит ковырять эту тему
я за отпуск много что освоил, скажу тебе что даже опять интересна стала IT тема.
А то был перио упаднеческий совсем, когда вообще не чего не делал, только в зал ходил
